services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    volumes:
      - .:/workspace
      - ./romfs:/romfs:ro
    command: bash -lc "python3 preprocessor.py '/romfs/cinnamon/data.win' && make"
    tty: true
    stdin_open: true
